# Generated by Django 4.2 on 2023-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_faculty_options_alter_subfaculty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Maqola', 'verbose_name_plural': '4. Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': '1. Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': '3. Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='subfaculty',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "2. Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='win',
            options={'verbose_name': 'Yutuq', 'verbose_name_plural': '5. Yutuqlar'},
        ),
    ]
