# Generated by Django 4.2 on 2023-06-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_article_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='base_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
