# Generated by Django 4.2 on 2023-06-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_article_is_main_article_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_book',
            field=models.FileField(blank=True, null=True, upload_to='students/'),
        ),
    ]
