# Generated by Django 4.2 on 2023-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_grade_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon raqam'),
        ),
    ]
