# Generated by Django 4.2 on 2023-06-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Baho'),
        ),
        migrations.AddField(
            model_name='win',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Baho'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(max_length=3000, verbose_name='Talaba uchun xat')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='students.student')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
