# Generated by Django 4.2 on 2023-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_article_grade_win_grade_alter_article_is_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='media/students/articles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_book',
            field=models.FileField(blank=True, null=True, upload_to='media/students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_or_idcart_file',
            field=models.FileField(blank=True, upload_to='media/students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, upload_to='media/students/'),
        ),
        migrations.AlterField(
            model_name='win',
            name='file',
            field=models.FileField(upload_to='media/students/wins'),
        ),
    ]
