# Generated by Django 4.2 on 2023-06-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_article_file_alter_student_grade_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': '6. Xabarlar'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_main',
        ),
    ]
