# Generated by Django 4.2 on 2023-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_message_options_remove_article_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/students/image'),
        ),
    ]
