# Generated by Django 4.2 on 2023-06-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.FloatField(default=0, verbose_name='Baho'),
        ),
    ]
