# Generated by Django 4.2 on 2023-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_article_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='grade',
            field=models.FloatField(default=0, verbose_name='Baho'),
        ),
    ]
