# Generated by Django 4.2 on 2023-06-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_article_grade_alter_win_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='students.article', verbose_name='Maqola nomi'),
        ),
        migrations.AddField(
            model_name='message',
            name='win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='students.win', verbose_name='Yutuq nomi'),
        ),
    ]
