# Generated by Django 4.2 on 2023-07-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_message_article_message_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('main', 'Asosiy maqola'), ('addition', "Qo'shimcha maqola")], max_length=8, null=True),
        ),
    ]
