# Generated by Django 4.2 on 2023-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='statute',
            field=models.FileField(blank=True, null=True, upload_to='media/grant/nizomlar/', verbose_name='Nizom'),
        ),
        migrations.AlterField(
            model_name='sciencedirection',
            name='letter_dekan',
            field=models.FileField(blank=True, null=True, upload_to='media/grant/dekan_tavsiyanoma/', verbose_name='Dekanlik hujjati'),
        ),
        migrations.AlterField(
            model_name='sciencedirection',
            name='letter_mudir',
            field=models.FileField(blank=True, null=True, upload_to='media/grant/mudir_tavsiyanoma/', verbose_name='Mudirlik hujjati'),
        ),
        migrations.AlterField(
            model_name='sciencedirection',
            name='rank_notebook',
            field=models.FileField(blank=True, null=True, upload_to='media/grant/reyting_daftarcha/', verbose_name='Reyting daftarcha'),
        ),
    ]
